### ISSUE TITLE
It is not working with angular 2.4.0

### ISSUE THREAD

**Issue by NikhilRadadiya** [zhantewei2/angular-carousel#2]
I'm trying to use it with angular 2.4.0 but it is giving me error:

```ERROR in C:/xampp/htdocs/travelz/src/app/app.module.ts (28,36): Cannot find module 'angular2-carousel-ztw/carousel-module.module'.)

ERROR in C:/xampp/htdocs/travelz/src/app/app.module.ts (28,36): Cannot find module 'angular2-carousel-ztw/carousel-module.module'.)

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'angular2-carousel-ztw/carousel-module.module' in 'C:\xampp\htdocs\travelz\src\app'
 @ ./src/app/app.module.ts 32:0-84
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

Can you please help?

**Comment by zhantewei2** [comment]
install :-
````shell
 npm install angular2-carousel-ztw --save
````
import it:
````js
 import {CarouselModule} from 'angular2-carousel-ztw/carousel.module';

**Comment by NikhilRadadiya** [comment]
@zhantewei2  Getting errors after doing this. 

```npm install angular2-carousel-ztw --save```
```import {CarouselModule} from 'angular2-carousel-ztw/carousel.module';```

Did already what you have mentioned
